# Configuration file for OpenAPI Generator, used by script/generate-client.sh
projectName: fitbit-web-api
packageName: fitbit_web_api
library: asyncio
packageUrl: https://github.com/allenporter/fitbit-web-api
